### ISSUE TITLE
Ohne Anmeldung: Mehrere Menupunkte auf der Landingpage sind ohne Funktion

### ISSUE THREAD

**Issue by dominikfladung** [fhswf/book_me#116]
**Describe the bug**
Bei Aufruf der Landingpage werden die folgenden Menupunkte ohne Funktion angezeigt:
 - Profile
 - My Account
 - Calendar Integration

**To Reproduce**
1. Gehe zu https://jupiter.fh-swf.de/meeting/landing
2. Klicke auf Menu-Icon
3. Klicke auf Profile
4. Klicke auf My Account
5. Klicke auf Calendar Integration

**Expected behavior**
Ohne Anmeldung sollten diese Menupunkte nicht dargestellt werden

**Screenshots**
![image](https://github.com/fhswf/book_me/assets/41169722/6dbc85ea-e564-4870-b741-6228e9e61e82)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox 
 - Version 117.0.1 (64-bit)

**Comment by cgawron** [comment]
Fixed: e4c88e8
